name: Daily Stock Scraper

on:
  schedule:
    - cron: '0 17 * * *' # Runs at 17:00 UTC (6 PM Nigeria)
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Puppeteer Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdrm2 \
            libgbm1 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libxkbcommon0 \
            libasound2t64 \
            wget \
            xdg-utils

      - name: Install Dependencies
        run: npm install

      - name: Run Scraper
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}  # ✅ Matches code
        run: |
          echo "🔍 Checking Mongo URI..."
          if [ -z "$MONGODB_URI" ]; then
            echo "❌ MONGODB_URI is missing!"
            exit 1
          fi
          node scraper.js
